server:
  port: 8994

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: db_contact_management
      auto-index-creation: true
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://192.168.2.6:8080/realms/avs-payment
            jwk-set-uri: http://192.168.2.6:8080/realms/avs-payment/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


core:
  service:
    url-core: http://localhost:8990/avs-core