server:
  port: 8995

spring:
  data:
    mongodb:
      host: avs-data
      port: 27017
      database: db_report_management
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.2.6:8080/auth/realms/avs-payment
          jwk-set-uri: http://192.168.2.6:8080/auth/realms/avs-payment/protocol/openid-connect/certs
  
  rabbitmq:
    host: avs-rabbit
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    default:
      queue-sms: message-queue
      queue-airtime: airtime-queue
    direct:
      queue:
        1: direct-queue-1
        2: campaign-queue
      exchange: direct-exchange
    direct-routing-key:
      1: direct-routing-key-1
      2: direct-routing-key-2

eureka:
  client:
    service-url:
      defaultZone: http://avs-registry:8761/eureka


core:
  service:
    url-core: http://192.168.2.8:8980/avs-core
